### ISSUE TITLE
Unclear documentation on how to access a specific email folder by name

### ISSUE THREAD

**Issue by yihsiaol** [contextio/contextio-ruby#65]
I'm trying to access a specific folder and check if it exists, specifically this API request:
http://context.io/docs/2.0/accounts/sources/folders#id-get

Because it's a resource collection, I assumed the way to access a specific ID was with the `:[]` method.

For example: `contextio.accounts[account_id].sources[0].folders[folder_name]`, but I get an error saying *NoMethodError: undefined method `primary_key' for ContextIO::Folder:Class*.

What is the proper way to access a specific folder using the gem?

EDIT:
The quick and dirty way is to test each folder for the given folder name...but that kinda defeats the purpose of having a unique ID.  :)
`folders.find { |folder| folder.name == target_name }`

**Comment by vijayj** [comment]
Please add this to the code so that it can help with the folder fetch..thanks

**Comment by kerinin** [comment]
I just cut a new version (2.1.0) with these changes
