### ISSUE TITLE
Gemspec Still Has Me In There

### ISSUE THREAD

**Issue by benhamill** [contextio/contextio-ruby#67]
https://github.com/contextio/contextio-ruby/blob/master/contextio.gemspec

The Gemspec still has my email address for the contact email. Probably it should be someone's work address. Prolly I should have put my own work address to begin with, but oh well. Can y'all take a sec to change it when you get a sec. Thanks. :smile:

**Comment by michaelbernstein** [comment]
Thanks for catching that Ben!
